name = "founderfinder"
type = "javascript"
account_id = "cffdf44b9e5c6d35ebeac1d15fe85958"
compatibility_date = "2025-07-21"
main = ".open-next/_worker.js"

[site]
bucket = ".open-next/assets"

[[d1_databases]]
binding = "DB"
database_name = "founderfinder"
database_id = "f224c904-145c-4b93-b3dc-aabbbba68149"

