name = "founderfinder"
account_id = "cffdf44b9e5c6d35ebeac1d15fe85958"
compatibility_date = "2025-07-21"
main = ".open-next/worker.js"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "founderfinder"
database_id = "f224c904-145c-4b93-b3dc-aabbbba68149"

[[r2_buckets]]
binding = "NEXT_INC_CACHE_R2_BUCKET"
bucket_name = "founderfinder-cache"
