name: Deploy to Cloudflare

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    env:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm install
          npm install --save-dev open-next@3.1.3

      - name: Add OpenNext config
        run: |
          echo 'export default { target: "cloudflare" };' > open-next.config.mjs

      - name: Build project
        run: npx open-next build

      - name: Deploy with Wrangler
        run: wrangler deploy .open-next/worker.js --name=founderfinder --compatibility-date=2024-09-23
