name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache node modules and Next.js cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            .next/cache
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.18.0

      - name: Install dependencies
        run: npm install

      - name: Build the project using OpenNext
        run: npx opennextjs-cloudflare build
        env:
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
          BASE_URL: ${{ secrets.BASE_URL }}
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}

      - name: Install Wrangler
        run: npm install -g wrangler @opennextjs/cloudflare

      - name: Push secrets to Cloudflare
        run: |
          echo "${{ secrets.POSTGRES_URL }}" | wrangler secret put POSTGRES_URL
          echo "${{ secrets.STRIPE_SECRET_KEY }}" | wrangler secret put STRIPE_SECRET_KEY
          echo "${{ secrets.STRIPE_WEBHOOK_SECRET }}" | wrangler secret put STRIPE_WEBHOOK_SECRET
          echo "${{ secrets.BASE_URL }}" | wrangler secret put BASE_URL
          echo "${{ secrets.AUTH_SECRET }}" | wrangler secret put AUTH_SECRET
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Deploy to Cloudflare Workers
        run: npm run deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
