name: Deploy OpenNext to Cloudflare

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2️⃣ Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.18.0

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Build OpenNext for Cloudflare
      - name: Build OpenNext for Cloudflare
        env:
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
          BASE_URL: ${{ secrets.BASE_URL }}
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
        run: npx opennextjs-cloudflare build

      # 5️⃣ Deploy Worker to Cloudflare (ESM) with R2 binding
      - name: Deploy Worker to Cloudflare (ESM)
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          curl -X PUT \
            "https://api.cloudflare.com/client/v4/accounts/${CLOUDFLARE_ACCOUNT_ID}/workers/scripts/founderfinder" \
            -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
            -F 'metadata={
              "main_module":"worker.js",
              "type":"esm",
              "bindings":[
                {
                  "name":"NEXT_INC_CACHE_R2_BUCKET",
                  "type":"r2_bucket",
                  "bucket_name":"founderfinder-cache"
                }
              ],
              "body_part":"script"
            };type=application/json' \
            -F "script=@.open-next/worker.js;type=application/javascript"

      # 6️⃣ Upload static assets to R2 (founderfinder-cache)
      - name: Upload static assets to R2 (founderfinder-cache)
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          set -e
          for file in $(find .open-next/assets -type f); do
            key="${file#.open-next/assets/}"
            mime_type=$(file --mime-type -b "$file")
            echo "Uploading $key ($mime_type)..."
            response=$(curl -s -X PUT \
              "https://api.cloudflare.com/client/v4/accounts/${CLOUDFLARE_ACCOUNT_ID}/r2/buckets/founderfinder-cache/objects/$key" \
              -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
              -H "Content-Type: $mime_type" \
              --data-binary @"$file")
            echo "$response" | grep -q '"success":true' || { echo "❌ Failed to upload $key"; exit 1; }
          done
