name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Build OpenNext for Cloudflare runtime
      - name: Build OpenNext (Cloudflare target)
        run: npx open-next@latest build --target=cloudflare

      # 5️⃣ Deploy to Cloudflare Workers
      - name: Deploy with Wrangler
        run: wrangler deploy .open-next/worker.js --name=founderfinder --compatibility-date=2024-09-23
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
